[versions]
compose-plugin = "1.8.2"
junit = "4.13.2"
kotlin = "2.2.0"
moko = "0.16.1"
kotlinxCoroutines = "1.10.2"
kotlinSerialization = "1.9.0"
json = "20250517"
jackson = "2.19.2"
turbine = "1.2.1"
coil = "3.3.0"
materialIcons = "1.7.3"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mvvm-compose = { module = "dev.icerock.moko:mvvm-compose", version.ref = "moko" }
mvvm-core = { module = "dev.icerock.moko:mvvm-core", version.ref = "moko" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }
org-json = { group = "org.json", name = "json", version.ref = "json" }
jackson-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
compose-material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIcons" }

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id =  "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}