[versions]
compose-plugin = "1.6.11"
junit = "4.13.2"
kotlin = "2.0.0"
moko = "0.16.1"
kotlinxCoroutines = "1.7.3"
kotlinSerialization = "1.6.1"
json = "20240303"
jackson = "2.17.1"
turbine = "1.1.0"
kover = "0.8.2"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mvvm-compose = { module = "dev.icerock.moko:mvvm-compose", version.ref = "moko" }
mvvm-core = { module = "dev.icerock.moko:mvvm-core", version.ref = "moko" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }
org-json = { group = "org.json", name = "json", version.ref = "json" }
jackson-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id =  "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
kover = { id =  "org.jetbrains.kotlinx.kover", version.ref = "kover"}
